# Site settings
title                     : Youngs Github Page
bio                       : '一日不作一日不食'
url                       : https://younggeun0.github.io
github-url                : younggeun0
github_username           : younggeun0
locale                    : ko_KR

# Build settings
markdown:           kramdown
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            false
highlighter:        rouge

# remote theme settings
remote_theme              : mmistakes/minimal-mistakes
minimal_mistakes_skin     : dark
plugins:
  - jekyll-feed

exclude: [README.md, Gemfile, Gemfile.lock, src, vendor]